"""Rapport de couverture : extraction technique distincte de validation pédagogique."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def main():
    sources=json.loads((ROOT/'content/sources.json').read_text());coverage=json.loads((ROOT/'data/processed/coverage.json').read_text());questions=json.loads((ROOT/'content/questions.json').read_text());rules=json.loads((ROOT/'content/pedagogy.json').read_text());rows=[]
    for source in sources:
        folder=ROOT/'data/processed'/source['id'];pages=[json.loads(p.read_text()) for p in sorted(folder.glob('page-*.json'))]
        word=folder/'document.json';record=json.loads(word.read_text()) if word.exists() else None
        rows.append(dict(id=source['id'],filename=source['filename'],role=source['role'],usage=source['pedagogical_usage'],extraction=next(c for c in coverage if c['id']==source['id']),empty_or_short_pages=[p['pdf_page'] for p in pages if len(p.get('text','').strip())<60],ocr_pages=sum(p['method']=='ocr' for p in pages),native_pages=sum(p['method']=='native' for p in pages),word_tables=sum(b['type']=='table' for b in record['blocks']) if record else 0,linked_pilot_questions=[q['id'] for q in questions if source['id'] in [s['id'] for s in q['sources']]],linked_rules=[r['id'] for r in rules if source['id'] in [s['id'] for s in r['sources']]],pedagogical_validation='pending',visual_validation='pending'))
    report=dict(documents=len(rows),pdf_pages=sum(r['extraction'].get('pages',0) for r in rows),word_blocks=sum(r['extraction'].get('blocks',0) for r in rows),sources=rows)
    (ROOT/'docs/corpus-audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
    lines=['# Rôle et couverture des 17 sources','', 'Audit technique de la première itération. Une extraction réussie ne signifie pas que la page est correcte, lisible ou validée. Les pages vides incluent parfois des couvertures et des pages blanches.','', '| Source | Fonction | Extraction | Questions du pilote | Règles |','|---|---|---|---:|---|']
    for r in rows:lines.append(f"| {r['filename']} | {r['usage']} | {r['extraction']['status']} | {len(r['linked_pilot_questions'])} | {', '.join(r['linked_rules']) or '—'} |")
    lines+=['','## Ce qui reste à exploiter','', 'Les sources sans question pilote liée ne sont pas écartées : leur extraction est disponible, mais la conception de leurs activités reste à réaliser. Les fiches d’exercices doivent être segmentées et liées à leurs images ; les corrigés et les difficultés doivent être validés. Les manuels de biologie serviront aux chapitres suivants.','', 'Les référentiels Word conservent l’ordre des paragraphes et les tableaux, avec les cellules. Leur segmentation structurelle reste à revoir : les cellules fusionnées peuvent répéter du texte. Les niveaux d’expression, d’outils et de méthodologie sont déjà présents dans le schéma des compétences et l’évaluation. Les répartitions d’examens du lycée ne sont pas appliquées à la 2AC.','', 'L’OCR a été réalisé en français. Les passages en arabe, les figures, les nombres et les tableaux issus des scans nécessitent une vérification visuelle. Aucun passage brut du corpus n’est automatiquement exposé au tutorat élève.','', 'La pagination imprimée de Collection Compétence reste à contrôler page par page ; le nombre de pages PDF ne suffit pas à établir la complétude.','', 'Le fichier corpus-audit.json donne les pages très courtes, les méthodes d’extraction, les tableaux Word et les rattachements du pilote.']
    (ROOT/'docs/SOURCE_USAGE.md').write_text('\n'.join(lines)+'\n')
    print(report['documents'],report['pdf_pages'],report['word_blocks'])
if __name__=='__main__':main()
